[program:minecraft]
command=./run.sh
daemon=true
directory=/opt/minecraft
autostart=true
autorestart=true
user=minecraft
stdout_logfile=/var/log/supervisor/minecraft-stdout.log
stderr_logfile=/var/log/supervisor/minecraft-stderr.log
