[program:minecraft]
command=/opt/minecraft/server/run.sh
directory=/opt/minecraft/server
autostart=true
autorestart=true
user=minecraft
stdout_logfile=/var/log/supervisor/minecraft-stdout.log
stderr_logfile=/var/log/supervisor/minecraft-stderr.log
